name: aarch64

on:
  # For testing purposes, removeme later
  pull_request:
  push:
    branches:
      - aarch64_ci_testphase
    tags:
      - ciflow/aarch64/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  linux-jammy-aarch64-py3_10-build:
    name: linux-jammy-aarch64-py3.10
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-jammy-aarch64-py3.10
      docker-image-name: pytorch-linux-jammy-aarch64-py3.10-gcc11
      runner: ARM64
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1, runner: "ARM64" },
        ]}

  linux-jammy-aarch64-py3_10-test:
    name: linux-jammy-aarch64-py3.10
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-jammy-aarch64-py3_10-build
    permissions:
      id-token: write
      contents: read
    with:
      build-environment: linux-jammy-aarch64-py3.10
      docker-image: ${{ needs.linux-jammy-aarch64-py3_10-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-jammy-aarch64-py3_10-build.outputs.test-matrix }}
